import os
import sys
import argparse
import subprocess
import asyncio
import edge_tts
import hashlib

async def generate_audio(text, output_path):
    """Generates high-quality TTS audio using edge-tts."""
    # Defaulting to a professional female voice (en-US-AvaNeural)
    # or male (en-US-GuyNeural)
    voice = "en-US-AvaNeural" if "female" in output_path.lower() else "en-US-GuyNeural"
    communicate = edge_tts.Communicate(text, voice)
    await communicate.save(output_path)

def run_sadtalker(audio_path, image_path, output_dir):
    """Runs the SadTalker inference."""
    # Convert paths to absolute so they work from within the SadTalker dir
    abs_audio = os.path.abspath(audio_path)
    abs_image = os.path.abspath(image_path)
    abs_out = os.path.abspath(output_dir)
    
    cmd = [
        "python", "inference.py",
        "--driven_audio", abs_audio,
        "--source_image", abs_image,
        "--result_dir", abs_out,
        "--preprocess", "full",
        "--enhancer", "gfpgan"
    ]
    
    print(f"Executing in SadTalker/: {' '.join(cmd)}")
    subprocess.run(cmd, check=True, cwd="SadTalker")

async def main():
    parser = argparse.ArgumentParser(description="SadTalker Worker Bridge")
    parser.add_argument("--text", required=True, help="Text to speak")
    parser.add_argument("--image", required=True, help="Path to source image")
    parser.add_argument("--out", required=True, help="Output filename")
    
    args = parser.parse_args()
    
    # Create temp directory for processing
    os.makedirs("temp_proc", exist_ok=True)
    text_hash = hashlib.md5(args.text.encode()).hexdigest()
    temp_audio = f"temp_proc/{text_hash}.mp3"
    
    print(f"Step 1: Generating Audio for '{args.text[:30]}...'")
    await generate_audio(args.text, temp_audio)
    
    print("Step 2: Running SadTalker Inference (GPU)...")
    run_sadtalker(temp_audio, args.image, "temp_results")
    
    # SadTalker saves to temp_results/<timestamp>.mp4 or temp_results/<timestamp>/*.mp4
    # We need to find the latest .mp4 and move it to args.out.
    import glob
    videos = glob.glob("temp_results/**/*.mp4", recursive=True)
    if not videos:
        print("Error: No video generated by SadTalker.")
        sys.exit(1)
        
    latest_video = max(videos, key=os.path.getctime)
    os.rename(latest_video, args.out)
    print(f"Step 3: Finalizing video at {args.out}")

if __name__ == "__main__":
    asyncio.run(main())
